apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: ##NodeInstanceRole##
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  {{if .AddIAMUser }}
  mapUsers: |
    - userarn: ##EKS_USER_ARN##
      username: ##EKS_USER_NAME##
      groups:
        - system:masters
  {{end}}