apiVersion: xl/v1
kind: Blueprint
metadata:
  projectName: AWS-Datalake
  description: |
    The blueprint deploys a data lake architecture to AWS using CloudFormation.
    XL Deploy does the provisioning and deployment, while XL Release orchestrates everything.
    Refer to https://docs.aws.amazon.com/solutions/latest/data-lake-solution
  author: XebiaLabs
  version: 1.0
spec:
  parameters:
  - name: S3BucketName
    description: What is the name of the S3 bucket where CloudFormation templates should be saved?
    default: data-lake
    type: Input
    pattern: "(([a-z0-9]|[a-z0-9][a-z0-9\\-]*[a-z0-9])\\.)*([a-z0-9]|[a-z0-9][a-z0-9\\-]*[a-z0-9]){3,63}"
  - name: AdministratorName
    description: What is the name of the Data Lake administrator user?
    default: admin
    type: Input
    pattern : ".+"
  - name: AdministratorEmail
    description: "Provide a valid email address where to send the generated Data Lake administrator credentials:"
    type: Input
    pattern: "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$"
  - name: CognitoDomain
    description: "Provide a name for the Cognito service domain (can only contain lower-case letters, numbers, and hyphens):"
    default: data-lake
    type: Input
    pattern : "[a-z0-9-]+"
  - name: UseAWSCredentialsFromSystem
    type: Confirm
    description: Do you want to use AWS credentials from ~/.aws/credentials file?
    dependsOnTrue: !fn aws.credentials().IsAvailable
  - name: AWSAccessKey
    type: Input
    secret: true
    description: What is the AWS Access Key ID?
    dependsOnFalse: UseAWSCredentialsFromSystem
    default: !fn aws.credentials().AccessKeyID
  - name: AWSAccessSecret
    type: Input
    secret: true
    description: What is the AWS Secret Access Key?
    dependsOnFalse: UseAWSCredentialsFromSystem
    default: !fn aws.credentials().SecretAccessKey
  - name: AWSRegion
    type: Select
    description: "Select the AWS region:"
    options:
      - us-east-2
      - us-east-1
      - us-west-2
      - ap-south-1
      - ap-northeast-2
      - ap-southeast-1
      - ap-southeast-2
      - ap-northeast-1
      - ca-central-1
      - eu-central-1
      - eu-west-1
      - eu-west-2
    default: us-east-2
    saveInXlVals: true

  files:
  - path: xebialabs.yaml
  - path: cloudformation/data-lake-artifacts.zip
  - path: cloudformation/data-lake-api.yaml
  - path: cloudformation/data-lake-services.yaml
  - path: cloudformation/data-lake-storage.yaml
  - path: cloudformation/data-lake-deploy-federated.master.yaml.tmpl
  - path: cloudformation/data-lake-deploy.master.yaml.tmpl
  - path: xebialabs/README.md.tmpl
  - path: xebialabs/xld-infrastructure.yaml.tmpl
  - path: xebialabs/xld-environment.yaml.tmpl
  - path: xebialabs/xlr-pipeline.yaml.tmpl
