apiVersion: xl/v1
kind: Blueprint
metadata:
  projectName: AWS-Datalake 
  description: |
    The blueprint deploys a data lake architecture to AWS using CloudFormation.
    XL deploy does the provisioning and deployment, while XL release orchestrates everything.
    Refer https://docs.aws.amazon.com/solutions/latest/data-lake-solution
  author: XebiaLabs
  version: 1.0
spec:
- name: S3BucketName
  description: The S3 bucket name to use for CloudFormation templates
  type: Input
  pattern: "(([a-z0-9]|[a-z0-9][a-z0-9\\-]*[a-z0-9])\\.)*([a-z0-9]|[a-z0-9][a-z0-9\\-]*[a-z0-9]){3,63}"
- name: AdministratorName
  description: Name of the Data Lake administrator
  type: Input
  pattern : ".+"
- name: AdministratorEmail
  description: A valid Email address for Data Lake administrator
  type: Input
  pattern: "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$"
- name: CognitoDomain
  description: Prefixed domain names can only contain lower-case letters, numbers, and hyphens
  type: Input
  pattern : "[a-z0-9-]+"
- name: UseAWSCredentialsFromSystem
  type: Confirm
  description: Do you want to use AWS credentials from ~/.aws/credentials file?
  dependsOnTrue: !fn aws.credentials().IsAvailable
- name: AWSAccessKey
  type: Input
  secret: true
  description: What is the AWS access key?
  dependsOnFalse: UseAWSCredentialsFromSystem
  default: !fn aws.credentials().AccessKeyID
- name: AWSAccessSecret
  type: Input
  secret: true
  description: What is the AWS secret?
  dependsOnFalse: UseAWSCredentialsFromSystem
  default: !fn aws.credentials().SecretAccessKey
- name: AWSRegion
  type: Select
  options:
    - !fn aws.regions(lambda)
  default: !fn aws.regions(lambda)[0]