answers-file: answers.yaml
expected-files:
- xebialabs.yaml
- README.md
- xebialabs/USAGE-composable-demo.md
- xebialabs/xld-environment-infrastructure.yaml
- xebialabs/xld-environment-environments.yaml
- xebialabs/xld-application-applications.yaml
- xebialabs/config.yaml
- docker/docker-compose.yml
