xl_mode: blueprint
with_answers:
  DockerHashiCorpBackend: VERSIONED
  DockerHashiCorpSecretPath: xebialabs/demo
  DockerHashiCorpRootToken: demo-root-token
  DockerHashiCorpKeys: key.one,key.two
expect:
  to_exist:
  - xebialabs/USAGE-hashicorp-vault.md
  - docker-hashicorp-vault/docker-compose.yaml
  - docker-hashicorp-vault/vault/Dockerfile
  - docker-hashicorp-vault/vault/script/provision.sh
  to_not_exist:
  - xebialabs.yaml
  - xebialabs/values.xlvals
  - xebialabs/secrets.xlvals
