apiVersion: xl/v1
kind: Blueprint

metadata:
  projectName: Azure-Microservice-AKS-with-JHipster
  description: |
    The blueprint deploys an e-commerce microservice application to Azure AKS.
    XL Deploy does the provisioning and deployment, while XL Release orchestrates everything.
  author: XebiaLabs
  version: 1.0

spec:
  parameters:
  - name: AppName
    type: Input
    description: What do you want to name the application in XLD/XLR?

  - name: ResourceGroup
    # Resource group names only allow alphanumeric characters, periods, underscores, hyphens and parenthesis and cannot end in a period
    type: Input
    description: "What do you want to name the Resource Group in Azure (Note: can be DESTROYED by Terraform at a later stage)?"
    pattern: "^[\\w._()-]{2,50}[\\w_()-]$"

    # Question: Can I make this optional and just skip it altogether?
  - name: AdminUsername
    # Cannot be 'admin'
    type: Input
    description: What username do you want to use to access the cluster (cannot be 'admin')?
    pattern: "^[[:alpha:]]+$"

  - name: AdminUsernameSSHKeyPath
    type: File
    description: What is the path to the public SSH key for the above user?

  - name: AKSRegion
    type: Select
    description: "Select the AKS region:"
    options:
    - eastasia
    - southeastasia
    - centralus
    - eastus
    - eastus2
    - westus
    - northcentralus
    - southcentralus
    - northeurope
    - westeurope
    - japanwest
    - japaneast
    - brazilsouth
    - australiaeast
    - australiasoutheast
    - southindia
    - centralindia
    - westindia
    - canadacentral
    - canadaeast
    - uksouth
    - ukwest
    - westcentralus
    - westus2
    - koreacentral
    - koreasouth
    - francecentral
    - francesouth
    - australiacentral
    - australiacentral2
    - southafricanorth
    - southafricawest

  - name: ProvisionCluster
    type: Confirm
    description: Do you want to provision a new Azure AKS cluster?

  - name: ClusterEndpoint
    type: Input
    description: What is the endpoint for the cluster, example https://104.155.109.230
    dependsOnFalse: ProvisionCluster

  - name: PasswordToken
    type: Input
    description: What is the token for accessing the cluster
    dependsOnFalse: ProvisionCluster
    secret: true

  - name: ClusterName
    type: Input
    description: What name do you want to give the cluster?
    pattern: "^[[:alpha:]][\\w-]{1,29}[\\w]$"

  - name: Namespace
    type: Input
    description: What namespace do you want to give the new cluster?
    default: xl-demo

  # Authentication
  - name: ClientID
    type: Input
    description: What is the client id (appId) of an existing Service Principal in Azure?

  - name: ClientSecret
    type: Input
    description: What is the secret for the above client id?
    secret: true

  - name: SubscriptionID
    type: Input
    description: What is your existing Azure subscription id?

  - name: TenantID
    type: Input
    description: What is your existing Azure tenant id?

  # Jenkins
  - name: enableCICD
    type: Confirm
    description: Do you want to enable CI/CD integration with Jenkins?

  - name: StoreAdminUsername
    type: Input
    description: Store Admin username
    value: admin

  - name: StoreAdminPassword
    type: Input
    description: Store Admin password
    value: admin
    secret: true

  - name: XLDUrlForXLR
    type: Input
    description: XL Deploy URL for XL Release (This will only be used in the XL Release template)
    default: http://xl-deploy:4516

  # For the Terraform backend storage
  - name: StorageAccountName
    type: Input
    description: Existing Azure storage account where Terraform will store its state (see README.md on how to create this)
    dependsOnTrue: ProvisionCluster

  - name: StorageContainerName
    type: Input
    description: "Container within the storage account:"
    default: terraform-state
    dependsOnTrue: ProvisionCluster

  - name: StorageAccessKey
    type: Input
    description: "One of the Azure access keys for accessing the storage:"
    dependsOnTrue: ProvisionCluster

  files:
  - path: xebialabs/xld-infra-env.yaml.tmpl
  - path: xebialabs/xld-terraform-apps.yaml.tmpl
  - path: xebialabs/xld-kubernetes-invoice-app.yaml.tmpl
  - path: xebialabs/xld-kubernetes-store-app.yaml.tmpl
  - path: xebialabs/xld-kubernetes-notification-app.yaml.tmpl
  - path: xebialabs/xlr-pipeline-ci-cd.yaml.tmpl
  - path: xebialabs/xlr-pipeline-destroy.yaml.tmpl
  - path: xebialabs/USAGE.md.tmpl
  - path: terraform/main.tf
    dependsOnTrue: ProvisionCluster
  - path: terraform/variables.tf.tmpl
    dependsOnTrue: ProvisionCluster
  - path: terraform/backend.tf.tmpl
    dependsOnTrue: ProvisionCluster
  - path: terraform/outputs.tf
    dependsOnTrue: ProvisionCluster
  - path: terraform/.gitignore
    dependsOnTrue: ProvisionCluster
  - path: terraform/aks/main.tf
    dependsOnTrue: ProvisionCluster
  - path: terraform/aks/variables.tf
    dependsOnTrue: ProvisionCluster
  - path: terraform/aks/outputs.tf
    dependsOnTrue: ProvisionCluster
  - path: xebialabs.yaml
# docker-compose setup for required tools
  - path: docker/docker-compose.yml.tmpl
  - path: docker/data/configure-xl-devops-platform.yaml
  - path: docker/jenkins/jenkins.yaml
