# test the default scenario
answers-file: answers-01.yaml
expected-files:
- xebialabs.yaml
- README.md
- xebialabs/USAGE-simple-demo-app.md
- xebialabs/xld-simple-demo-app-applications.yaml
- xebialabs/xld-simple-demo-app-infrastructure.yaml
- xebialabs/xld-simple-demo-app-environments.yaml
- xebialabs/xlr-simple-demo-app-pipeline-ci-cd.yaml
- xebialabs/xlr-simple-demo-app-pipeline-destroy.yaml
- docker/docker-compose.yml
- docker/data/configure-xl-devops-platform.yaml
