xl_mode: blueprint
with_answers:
  AppName: test-project
  ContainerPort: 80
  HostPort: 8181
  BackendDockerImage: xebialabsunsupported/rest-o-rant-api
  FrontendDockerImage: xebialabsunsupported/rest-o-rant-web
  GenerateDockerComposeSetup: true
expect:
  to_exist:
  - xebialabs.yaml
  - README.md
  - xebialabs/USAGE-simple-demo-app.md
  - xebialabs/xld-simple-demo-app-applications.yaml
  - xebialabs/xld-simple-demo-app-infrastructure.yaml
  - xebialabs/xld-simple-demo-app-environments.yaml
  - xebialabs/xlr-simple-demo-app-pipeline-ci-cd.yaml
  - xebialabs/xlr-simple-demo-app-pipeline-destroy.yaml
  - docker/docker-compose.yml
  - docker/data/configure-xl-devops-platform.yaml
