apiVersion: xl/v1
kind: Blueprint

metadata:
  projectName: Azure-Basic-AKS-Cluster-Pipeline
  description: |
    The blueprint provision a basic XLR instance to control the Azure-Basic-AKS blueprint. It takes over the manual deployment that is done within the XLD interface.
  author: XebiaLabs
  version: 1.0
  instructions: Please read the generated file "xebialabs/USAGE-azure-basic-aks-cluster-pipeline.md" for further usage instructions.

spec:
  parameters:
  - name: ClusterName
    type: Input
    description: "Use the same cluster name as you did for the basic cluster:"

  - name: Prefix
    type: Input
    description: "Use the same prefix as you did for the basic cluster:"
    pattern: "([a-z0-9-]+-)+"

  - name: XLDUrlForXLR
    type: Input
    description: XL Deploy URL for XL Release (This will only be used in the XL Release template)
    default: http://xl-deploy:4516

  - name: Namespace
    type: Input
    value: default

  files:
  # XebiaLabs
  - path: xebialabs/USAGE-azure-basic-aks-cluster-pipeline.md.tmpl
  - path: xebialabs/azure-basic-aks-cluster-pipeline.yaml.tmpl
