xl_mode: blueprint
with_answers:
  AppName: myapp
  DockerImage: httpd
  DockerImageTag: latest
  KubernetesResourcesFile: ../kubernetes-application/httpd.yaml
  Namespace: default
expect:
  to_exist:
  - README.md
  - xebialabs.yaml
  - xebialabs/values.xlvals
  - xebialabs/secrets.xlvals
  - xebialabs/USAGE-application.md
  - xebialabs/xld-application-applications.yaml
  - kubernetes-application/deployment.yaml
