apiVersion: xl/v1
kind: Blueprint

metadata:
  projectName: AWS-Microservice-EKS-with-JHipster
  description: |
    The blueprint deploys an e-commerce microservice application to AWS EKS.
    XL deploy does the provisioning and deployment, while XL release orchestrates everything.
  author: XebiaLabs
  version: 1.0

spec:
# General variables
- name: AppName
  type: Input
  description: What is the name of the application?

# AWS specific variables
- name: UseAWSCredentialsFromSystem
  type: Confirm
  description: Do you want to use AWS credentials from ~/.aws/credentials file?
  dependsOnTrue: !fn aws.credentials().IsAvailable
- name: AWSAccessKey
  type: Input
  secret: true
  description: What is the AWS access key?
  dependsOnFalse: UseAWSCredentialsFromSystem
  default: !fn aws.credentials().AccessKeyID
- name: AWSAccessSecret
  type: Input
  secret: true
  description: What is the AWS secret?
  dependsOnFalse: UseAWSCredentialsFromSystem
  default: !fn aws.credentials().SecretAccessKey
- name: AWSRegion #options are set manually because EKS service is not registered within AWS GO SDK
  type: Select
  description: What is the AWS region?
  options:
    - eu-west-1
    - us-east-1
    - us-west-2
- name: ProvisionCluster
  type: Confirm
  description: Do you want to provision a new AWS EKS cluster?
- name: ClusterName
  type: Input
  description: What is the name of the cluster?
- name: ClusterEndpoint
  type: Input
  dependsOnFalse: ProvisionCluster
  description: What is the endpoint for the cluster, example https://cluster1.k8s.abc.org
- name: Namespace
  type: Input
  description: What is the name of the namespace? should be same as used in Kubernetes files.
  default: default
