apiVersion: xl/v1
kind: Blueprint

metadata:
  projectName: Azure-AKS-Basic
  description: |
    The blueprint provisions a very basic Azure AKS cluster. XL Deploy does the provisioning.
  author: XebiaLabs
  version: 1.0
  instructions: Please read the generated file "xebialabs/USAGE-azure-basic-aks-cluster.md" for further usage instructions.

spec:
  parameters:
  # ############################################################################
  # Access and authorization
  # ############################################################################
  - name: ClientID
    type: Input
    description: What is the client id (appId) of an existing Service Principal in Azure?

  - name: ClientSecret
    type: Input
    description: What is the secret (password) for that client id?
    secret: true

  - name: SubscriptionID
    type: Input
    description: What is your existing Azure subscription id?

  - name: TenantID
    type: Input
    description: What is your existing Azure tenant id?

  # ############################################################################
  # Resource group under which the cluster will be created
  # ############################################################################
  - name: ResourceGroup
    type: Input
    description: What do you want to name the resource group?

  - name: ResourceGroupLocation
    type: Select
    description: "Select where this resource group will go:"
    options:
    - eastasia
    - southeastasia
    - centralus
    - eastus
    - eastus2
    - westus
    - northcentralus
    - southcentralus
    - northeurope
    - westeurope
    - japanwest
    - japaneast
    - brazilsouth
    - australiaeast
    - australiasoutheast
    - southindia
    - centralindia
    - westindia
    - canadacentral
    - canadaeast
    - uksouth
    - ukwest
    - westcentralus
    - westus2
    - koreacentral
    - koreasouth
    - francecentral
    - francesouth
    - australiacentral
    - australiacentral2
    - southafricanorth
    - southafricawest

  - name: ClusterName
    type: Input
    description: What do you want to name the cluster?

  - name: Prefix
    type: Input
    description: "Specify the application prefix (use the default if you're not sure):"
    default: azure-aks-
    pattern: "([a-z0-9-]+-)+"

  files:
  # XebiaLabs
  - path: xebialabs/USAGE-azure-basic-aks-cluster.md.tmpl
  - path: xebialabs/azure-basic-aks-cluster.yaml.tmpl
  # Terraform
  - path: terraform-azure-basic-aks-cluster/.gitignore
  - path: terraform-azure-basic-aks-cluster/main.tf
  - path: terraform-azure-basic-aks-cluster/output.tf
  - path: terraform-azure-basic-aks-cluster/variables.tf
