apiVersion: xl/v1
kind: Blueprint

metadata:
  projectName: AWS-Microservice-EKS
  description: |
    The blueprint deploys a microservice application to AWS EKS.
    XL deploy does the provisioning and deployment, while XL release orchestrates everything.
  author: XebiaLabs
  version: 1.0

spec:
# General variables
- name: AppName
  type: Input
  description: Enter name of the application

# AWS specific variables
- name: UseAWSCredentialsFromSystem
  type: Confirm
  description: Do you want to use AWS credentials from ~/.aws/credentials file?
  dependsOnTrue: !fn aws.credentials().IsAvailable
- name: AWSAccessKey
  type: Input
  secret: true
  description: What is the AWS access key?
  dependsOnFalse: UseAWSCredentialsFromSystem
  default: !fn aws.credentials().AccessKeyID
- name: AWSAccessSecret
  type: Input
  secret: true
  description: What is the AWS secret?
  dependsOnFalse: UseAWSCredentialsFromSystem
  default: !fn aws.credentials().SecretAccessKey
- name: AWSRegion #options are set manually because EKS service is not registered within AWS GO SDK
  type: Select
  description: Select AWS region
  options:
    - eu-west-1
    - us-east-1
    - us-east-2
    - us-west-2
- name: ProvisionCluster
  type: Confirm
  description: Provision a new AWS EKS cluster?
- name: ClusterName
  type: Input
  description: AWS EKS cluster name to create/use
- name: ClusterEndpoint
  type: Input
  dependsOnFalse: ProvisionCluster
  description: URL for RESTful interface provided by API Server, example https://cluster1.k8s.abc.org
- name: UseExistingNamespace
  type: Confirm
  dependsOnFalse: ProvisionCluster
  description: Use and existing K8s namespace?
- name: Namespace
  type: Input
  description: Enter the name of the namespace to create/use
  default: default

# XLD/XLR specific variables
- name: XLDServerURL
  type: Input
  default: http://xld:4516
  description: XL-Deploy URL
- name: XLDUsername
  type: Input
  default: admin
  description: XL-Deploy user name
- name: XLDPassword
  type: Input
  secret: true
  description: XL-Deploy user password
- name: XLRUsername
  type: Input
  default: admin
  description: XL-Release user name
- name: XLRPassword
  type: Input
  secret: true
  description: XL-Release user password
- name: XLRScriptUsername
  type: Input
  value: admin
  description: What is the XLR Script username?
  secret: true
- name: XLRScriptUserPassword
  type: Input
  value: admin
  description: What is the XLR Script user password?
  secret: true

# App specific variables
- name: Modules
  type: List
  description: Enter number of k8s modules you want to define
  children:
    - name: ModuleName
      type: Input
      description: K8s module name
    - name: Deployables
      type: List
      description: Enter number of deployables you want to define for k8s module
      default: 1
      children:
        - name: DeployableName
          type: Input
          description: XLD deployable name
        - name: K8sYamlPath
          type: Input
          description: K8s yaml file path to be used from XLD, should be a relative path