apiVersion: xl/v1
kind: Blueprint
metadata:
  projectName: Extended ServiceNow Pipeline
  description: |
    This is a more interesting release template that uses ServiceNow.
  author: XebiaLabs
  version: 1.0
parameters:
- name: FolderName
  type: Input
  description: What is the Folder should the XLR template be stored?
- name: AppName
  type: Input
  description: What is the Application name?
- name: SNOW_URL
  type: Input
  description: What is the Service Now URL?
- name: SNOW_USERNAME
  type: Input
  secret: false
  description: What is the Service Now User Name?
- name: SNOW_PASSWORD
  type: Input
  secret: true
  description: What is the Service Now Password?
- name: JIRA_URL
  type: Input
  description: What is the JIRA URL?
- name: JIRA_USERNAME
  type: Input
  secret: false
  description: What is the JIRA User Name?
- name: JIRA_PASSWORD
  type: Input
  secret: true
  description: What is the JIRA Password?


files:
- path: xebialabs/xlr-configuration.yaml.tmpl
- path: xebialabs/xlr-pipeline.yaml.tmpl
- path: xebialabs.yaml
